# docker-compose build
# docker-compose up -d
version: '3'

# TODO: access external full-text-rss!

services:
  docker_redis:
    build: redis
    container_name: redis
    image: redis
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - hn-feeds
      
  app:
    container_name: hn-feeds
    build: .
    restart: unless-stopped
    ports:
      - 8254:80
    env_file:
      - ./.env
    depends_on:
      - docker_redis
    extra_hosts:
      - "rss_feed_host:host-gateway"
    networks:
      - hn-feeds

volumes:
  redis:

networks:
  hn-feeds:
    name: hn-feeds
